### ISSUE TITLE
macOS file

### ISSUE THREAD

**Issue by dosipod** [zak-45/WLEDVideoSync#2]
Just because I seen you post that in multiple places I thought to try it  , what is the macOS file format tar or dmg ? The way you packaged that does not work as it will just be opened in the default text editor

**Comment by zak-45** [comment]
This should be an app bundle, packaged by Nuitka.  The one  you download need to be set as executable, chmod u+x on Mac if I'm not wrong. This will extract the portable app into the WLEDVideoSync folder.

**Comment by dosipod** [comment]
Thx for updating the page , Not sure the minimum system requirement is listed but does not seem to be targeted  for old machines 
![image](https://github.com/user-attachments/assets/7827a5f3-7e30-4145-b47c-a8f447817fa7)

**Comment by zak-45** [comment]
The doc had already contains this info, but put it into other places, just to not miss it !!
I would say that your HW config should be enough, not sure about SW config (x32 or x64 ...?). This has been tested on old PC but with linux : https://discord.com/channels/700041398778331156/861288538863960095/1283366367344459899
I do not have any MacOs expertise so will not be able to provide you with any valuable help.
I will close this one.
On your side, feel free to provide feedback in case of any success, always apreciated.

**Comment by dosipod** [comment]
Its the processor as some with Intel (X86_64) or M1 (ARM) .Take a look at the example for releases used in ledfx  so not to send others on a wild guess chase so better to list that on the site 
https://github.com/LedFx/LedFx/releases/tag/v2.0.105

**Comment by zak-45** [comment]
right. done. thx.
